# Generated by Django 3.2.5 on 2021-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexapp', '0003_alter_userhistory_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdata',
            name='date',
            field=models.DateField(),
        ),
    ]
