# Generated by Django 3.2.5 on 2021-07-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexapp', '0004_alter_tradingdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=10)),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('chg_percent', models.FloatField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
