# Generated by Django 3.2.5 on 2021-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexapp', '0005_predictiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiondata',
            name='opn',
            field=models.FloatField(default=0),
        ),
    ]
