# Generated by Django 3.2.5 on 2021-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexapp', '0006_predictiondata_opn'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
